### ISSUE TITLE
Drive link is broken

### ISSUE THREAD

**Issue by lefteris12** [zy511361103/GADE#1]
Hello,
I'm interested in this dataset but the link seems to be broken: https://drive.google.com/file/d/1aYPNVCVIBs6c9er_bhT3U8YzClF-EDsR/viewusp=sharing. Could you fix it?
Thanks

**Comment by GuangtaoLyu** [comment]
> Hello, I'm interested in this dataset but the link seems to be broken: https://drive.google.com/file/d/1aYPNVCVIBs6c9er_bhT3U8YzClF-EDsR/viewusp=sharing. Could you fix it? Thanks

broken
